/*
 *
 *  * Copyright 2020 New Relic Corporation. All rights reserved.
 *  * SPDX-License-Identifier: Apache-2.0
 *
 */

package java.sql;

import com.newrelic.agent.bridge.AgentBridge;
import com.newrelic.agent.bridge.datastore.DatastoreMetrics;
import com.newrelic.agent.bridge.datastore.JdbcHelper;
import com.newrelic.api.agent.NewRelic;
import com.newrelic.api.agent.Trace;
import com.newrelic.api.agent.weaver.MatchType;
import com.newrelic.api.agent.weaver.NewField;
import com.newrelic.api.agent.weaver.Weave;
import com.newrelic.api.agent.weaver.Weaver;

import java.util.HashMap;

@Weave(originalName = "java.sql.Statement", type = MatchType.Interface)
public abstract class Statement_Weaved {
    @NewField
    String sampleBatchSql = null;

    public void addBatch(String sql) throws SQLException {
        if (sampleBatchSql == null) {
            sampleBatchSql = sql;
        }
        Weaver.callOriginal();
    }

    @Trace(leaf = true)
    public int [] executeBatch() throws SQLException {
        String sql = sampleBatchSql;
        if (sql == null) {
            sql = JdbcHelper.getSql((Statement) this);
        }

        int [] results = Weaver.callOriginal();
        String batchSql = sql;
        if (results != null && sql != null) {
            AgentBridge.getAgent().getTracedMethod().addCustomAttribute("batch_size", results.length);
            batchSql = String.format("/* NRBATCH:%d */ %s", results.length, sql);
        }
        DatastoreMetrics.noticeSql(getConnection(), batchSql, null);

        return results;
    }

    @Trace(leaf = true)
    public ResultSet executeQuery(String sql) throws SQLException {
        sql = JdbcHelper.addSqlMetadataCommentIfNeeded(sql);
        DatastoreMetrics.noticeSql(getConnection(), sql, null);
        return Weaver.callOriginal();
    }

    @Trace(leaf = true)
    public int executeUpdate(String sql) throws SQLException {
        sql = JdbcHelper.addSqlMetadataCommentIfNeeded(sql);
        DatastoreMetrics.noticeSql(getConnection(), sql, null);
        return Weaver.callOriginal();
    }

    @Trace(leaf = true)
    public boolean execute(String sql) throws SQLException {
        sql = JdbcHelper.addSqlMetadataCommentIfNeeded(sql);
        DatastoreMetrics.noticeSql(getConnection(), sql, null);
        return Weaver.callOriginal();
    }

    @Trace(leaf = true)
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        sql = JdbcHelper.addSqlMetadataCommentIfNeeded(sql);
        DatastoreMetrics.noticeSql(getConnection(), sql, null);
        return Weaver.callOriginal();
    }

    @Trace(leaf = true)
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        sql = JdbcHelper.addSqlMetadataCommentIfNeeded(sql);
        DatastoreMetrics.noticeSql(getConnection(), sql, null);
        return Weaver.callOriginal();
    }

    @Trace(leaf = true)
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        sql = JdbcHelper.addSqlMetadataCommentIfNeeded(sql);
        DatastoreMetrics.noticeSql(getConnection(), sql, null);
        return Weaver.callOriginal();
    }

    @Trace(leaf = true)
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        sql = JdbcHelper.addSqlMetadataCommentIfNeeded(sql);
        DatastoreMetrics.noticeSql(getConnection(), sql, null);
        return Weaver.callOriginal();
    }

    @Trace(leaf = true)
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        sql = JdbcHelper.addSqlMetadataCommentIfNeeded(sql);
        DatastoreMetrics.noticeSql(getConnection(), sql, null);
        return Weaver.callOriginal();
    }

    @Trace(leaf = true)
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        sql = JdbcHelper.addSqlMetadataCommentIfNeeded(sql);
        DatastoreMetrics.noticeSql(getConnection(), sql, null);
        return Weaver.callOriginal();
    }

    public abstract Connection getConnection() throws SQLException;
}
