/*
 *
 *  * Copyright 2020 New Relic Corporation. All rights reserved.
 *  * SPDX-License-Identifier: Apache-2.0
 *
 */

package com.newrelic.agent.extension.beans;

import java.util.ArrayList;
import java.util.List;

/**
 * This file used to be auto-generated by jax-b, but since removing that dependency, and given how stable the format has been,
 * it's fine to include it statically.
 *
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="instrumentation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pointcut" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nameTransaction" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;choice>
 *                               &lt;element name="methodAnnotation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;sequence>
 *                                 &lt;choice>
 *                                   &lt;element name="className">
 *                                     &lt;complexType>
 *                                       &lt;simpleContent>
 *                                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                           &lt;attribute name="includeSubclasses" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                                         &lt;/extension>
 *                                       &lt;/simpleContent>
 *                                     &lt;/complexType>
 *                                   &lt;/element>
 *                                   &lt;element name="interfaceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                 &lt;/choice>
 *                                 &lt;element name="method" maxOccurs="unbounded">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;choice>
 *                                           &lt;element name="returnType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                           &lt;sequence>
 *                                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                             &lt;element name="parameters" minOccurs="0">
 *                                               &lt;complexType>
 *                                                 &lt;complexContent>
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                     &lt;sequence>
 *                                                       &lt;element name="type" maxOccurs="unbounded" minOccurs="0">
 *                                                         &lt;complexType>
 *                                                           &lt;simpleContent>
 *                                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                               &lt;attribute name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                             &lt;/extension>
 *                                                           &lt;/simpleContent>
 *                                                         &lt;/complexType>
 *                                                       &lt;/element>
 *                                                     &lt;/sequence>
 *                                                   &lt;/restriction>
 *                                                 &lt;/complexContent>
 *                                               &lt;/complexType>
 *                                             &lt;/element>
 *                                           &lt;/sequence>
 *                                         &lt;/choice>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/sequence>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                           &lt;attribute name="transactionStartPoint" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="metricNameFormat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="excludeFromTransactionTrace" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="leaf" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="ignoreTransaction" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                           &lt;attribute name="transactionType" default="background">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="background"/>
 *                                 &lt;enumeration value="web"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="metricPrefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}double" default="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public class Extension {
    protected Extension.Instrumentation instrumentation;
    protected String name;
    protected Boolean enabled;
    protected Double version;

    /**
     * Gets the value of the instrumentation property.
     *
     * @return possible object is {@link Extension.Instrumentation }
     */
    public Extension.Instrumentation getInstrumentation() {
        return instrumentation;
    }

    /**
     * Sets the value of the instrumentation property.
     *
     * @param value allowed object is {@link Extension.Instrumentation }
     */
    public void setInstrumentation(Extension.Instrumentation value) {
        instrumentation = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     */
    public void setName(String value) {
        name = value;
    }

    /**
     * Gets the value of the enabled property.
     *
     * @return possible object is {@link Boolean }
     */
    public boolean isEnabled() {
        if (enabled == null) {
            return true;
        } else {
            return enabled;
        }
    }

    /**
     * Sets the value of the enabled property.
     *
     * @param value allowed object is {@link Boolean }
     */
    public void setEnabled(Boolean value) {
        enabled = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link Double }
     */
    public double getVersion() {
        if (version == null) {
            return 1.0D;
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link Double }
     */
    public void setVersion(Double value) {
        version = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pointcut" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nameTransaction" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;choice>
     *                     &lt;element name="methodAnnotation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                     &lt;sequence>
     *                       &lt;choice>
     *                         &lt;element name="className">
     *                           &lt;complexType>
     *                             &lt;simpleContent>
     *                               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                 &lt;attribute name="includeSubclasses" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                               &lt;/extension>
     *                             &lt;/simpleContent>
     *                           &lt;/complexType>
     *                         &lt;/element>
     *                         &lt;element name="interfaceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                       &lt;/choice>
     *                       &lt;element name="method" maxOccurs="unbounded">
     *                         &lt;complexType>
     *                           &lt;complexContent>
     *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                               &lt;choice>
     *                                 &lt;element name="returnType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                 &lt;sequence>
     *                                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                   &lt;element name="parameters" minOccurs="0">
     *                                     &lt;complexType>
     *                                       &lt;complexContent>
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                           &lt;sequence>
     *                                             &lt;element name="type" maxOccurs="unbounded" minOccurs="0">
     *                                               &lt;complexType>
     *                                                 &lt;simpleContent>
     *                                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                                     &lt;attribute name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                                   &lt;/extension>
     *                                                 &lt;/simpleContent>
     *                                               &lt;/complexType>
     *                                             &lt;/element>
     *                                           &lt;/sequence>
     *                                         &lt;/restriction>
     *                                       &lt;/complexContent>
     *                                     &lt;/complexType>
     *                                   &lt;/element>
     *                                 &lt;/sequence>
     *                               &lt;/choice>
     *                             &lt;/restriction>
     *                           &lt;/complexContent>
     *                         &lt;/complexType>
     *                       &lt;/element>
     *                     &lt;/sequence>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *                 &lt;attribute name="transactionStartPoint" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="metricNameFormat" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="excludeFromTransactionTrace" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="leaf" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="ignoreTransaction" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                 &lt;attribute name="transactionType" default="background">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="background"/>
     *                       &lt;enumeration value="web"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="metricPrefix" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public static class Instrumentation {
        protected List<Extension.Instrumentation.Pointcut> pointcut;
        protected String metricPrefix;

        /**
         * Gets the value of the pointcut property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the object.
         * This is why there is not a <CODE>set</CODE> method for the pointcut property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPointcut().add(newItem);
         * </pre>
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Extension.Instrumentation.Pointcut }
         */
        public List<Extension.Instrumentation.Pointcut> getPointcut() {
            if (pointcut == null) {
                pointcut = new ArrayList<>();
            }
            return pointcut;
        }

        /**
         * Gets the value of the metricPrefix property.
         *
         * @return possible object is {@link String }
         */
        public String getMetricPrefix() {
            return metricPrefix;
        }

        /**
         * Sets the value of the metricPrefix property.
         *
         * @param value allowed object is {@link String }
         */
        public void setMetricPrefix(String value) {
            metricPrefix = value;
        }

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nameTransaction" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;choice>
         *           &lt;element name="methodAnnotation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *           &lt;sequence>
         *             &lt;choice>
         *               &lt;element name="className">
         *                 &lt;complexType>
         *                   &lt;simpleContent>
         *                     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                       &lt;attribute name="includeSubclasses" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *                     &lt;/extension>
         *                   &lt;/simpleContent>
         *                 &lt;/complexType>
         *               &lt;/element>
         *               &lt;element name="interfaceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *             &lt;/choice>
         *             &lt;element name="method" maxOccurs="unbounded">
         *               &lt;complexType>
         *                 &lt;complexContent>
         *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                     &lt;choice>
         *                       &lt;element name="returnType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                       &lt;sequence>
         *                         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                         &lt;element name="parameters" minOccurs="0">
         *                           &lt;complexType>
         *                             &lt;complexContent>
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                 &lt;sequence>
         *                                   &lt;element name="type" maxOccurs="unbounded" minOccurs="0">
         *                                     &lt;complexType>
         *                                       &lt;simpleContent>
         *                                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                           &lt;attribute name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                         &lt;/extension>
         *                                       &lt;/simpleContent>
         *                                     &lt;/complexType>
         *                                   &lt;/element>
         *                                 &lt;/sequence>
         *                               &lt;/restriction>
         *                             &lt;/complexContent>
         *                           &lt;/complexType>
         *                         &lt;/element>
         *                       &lt;/sequence>
         *                     &lt;/choice>
         *                   &lt;/restriction>
         *                 &lt;/complexContent>
         *               &lt;/complexType>
         *             &lt;/element>
         *           &lt;/sequence>
         *         &lt;/choice>
         *       &lt;/sequence>
         *       &lt;attribute name="transactionStartPoint" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="metricNameFormat" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="excludeFromTransactionTrace" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="leaf" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="ignoreTransaction" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *       &lt;attribute name="transactionType" default="background">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="background"/>
         *             &lt;enumeration value="web"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        public static class Pointcut {
            protected Extension.Instrumentation.Pointcut.NameTransaction nameTransaction;
            protected String methodAnnotation;
            protected Extension.Instrumentation.Pointcut.ClassName className;
            protected String interfaceName;
            protected List<Extension.Instrumentation.Pointcut.Method> method;
            protected boolean transactionStartPoint;
            protected String metricNameFormat;
            protected boolean excludeFromTransactionTrace;
            protected boolean leaf;
            protected boolean ignoreTransaction;
            protected boolean traceLambda;
            protected String pattern;
            protected boolean includeNonstatic;
            protected List<String> traceReturnTypeDescriptors;
            protected String transactionType;

            /**
             * Gets the value of the nameTransaction property.
             *
             * @return possible object is {@link Extension.Instrumentation.Pointcut.NameTransaction }
             */
            public Extension.Instrumentation.Pointcut.NameTransaction getNameTransaction() {
                return nameTransaction;
            }

            /**
             * Sets the value of the nameTransaction property.
             *
             * @param value allowed object is {@link Extension.Instrumentation.Pointcut.NameTransaction }
             */
            public void setNameTransaction(Extension.Instrumentation.Pointcut.NameTransaction value) {
                nameTransaction = value;
            }

            /**
             * Gets the value of the methodAnnotation property.
             *
             * @return possible object is {@link String }
             */
            public String getMethodAnnotation() {
                return methodAnnotation;
            }

            /**
             * Sets the value of the methodAnnotation property.
             *
             * @param value allowed object is {@link String }
             */
            public void setMethodAnnotation(String value) {
                methodAnnotation = value;
            }

            /**
             * Gets the value of the className property.
             *
             * @return possible object is {@link Extension.Instrumentation.Pointcut.ClassName }
             */
            public Extension.Instrumentation.Pointcut.ClassName getClassName() {
                return className;
            }

            /**
             * Sets the value of the className property.
             *
             * @param value allowed object is {@link Extension.Instrumentation.Pointcut.ClassName }
             */
            public void setClassName(Extension.Instrumentation.Pointcut.ClassName value) {
                className = value;
            }

            /**
             * Gets the value of the interfaceName property.
             *
             * @return possible object is {@link String }
             */
            public String getInterfaceName() {
                return interfaceName;
            }

            /**
             * Sets the value of the interfaceName property.
             *
             * @param value allowed object is {@link String }
             */
            public void setInterfaceName(String value) {
                interfaceName = value;
            }

            /**
             * Gets the value of the method property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the object.
             * This is why there is not a <CODE>set</CODE> method for the method property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMethod().add(newItem);
             * </pre>
             *
             * <p>
             * Objects of the following type(s) are allowed in the list {@link Extension.Instrumentation.Pointcut.Method }
             */
            public List<Extension.Instrumentation.Pointcut.Method> getMethod() {
                if (method == null) {
                    method = new ArrayList<>();
                }
                return method;
            }

            /**
             * Gets the value of the transactionStartPoint property.
             *
             * @return possible object is {@link Boolean }
             */
            public boolean isTransactionStartPoint() {
                return transactionStartPoint;
            }

            /**
             * Sets the value of the transactionStartPoint property.
             *
             * @param value allowed object is {@link Boolean }
             */
            public void setTransactionStartPoint(Boolean value) {
                transactionStartPoint = value;
            }

            /**
             * Gets the value of the metricNameFormat property.
             *
             * @return possible object is {@link String }
             */
            public String getMetricNameFormat() {
                return metricNameFormat;
            }

            /**
             * Sets the value of the metricNameFormat property.
             *
             * @param value allowed object is {@link String }
             */
            public void setMetricNameFormat(String value) {
                metricNameFormat = value;
            }

            /**
             * Gets the value of the excludeFromTransactionTrace property.
             *
             * @return possible object is {@link Boolean }
             */
            public boolean isExcludeFromTransactionTrace() {
                return excludeFromTransactionTrace;
            }

            /**
             * Sets the value of the excludeFromTransactionTrace property.
             *
             * @param value allowed object is {@link Boolean }
             */
            public void setExcludeFromTransactionTrace(Boolean value) {
                excludeFromTransactionTrace = value;
            }

            /**
             * Gets the value of the leaf property.
             *
             * @return possible object is {@link Boolean }
             */
            public boolean isLeaf() {
                return leaf;
            }

            /**
             * Sets the value of the leaf property.
             *
             * @param value allowed object is {@link Boolean }
             */
            public void setLeaf(Boolean value) {
                leaf = value;
            }

            /**
             * Gets the value of the ignoreTransaction property.
             *
             * @return possible object is {@link Boolean }
             */
            public boolean isIgnoreTransaction() {
                return ignoreTransaction;
            }

            /**
             * Sets the value of the ignoreTransaction property.
             *
             * @param value allowed object is {@link Boolean }
             */
            public void setIgnoreTransaction(Boolean value) {
                ignoreTransaction = value;
            }

            /**
             * Gets the value of the traceLambda property.
             *
             * @return possible object is {@link Boolean }
             */
            public boolean isTraceLambda() {
                return traceLambda;
            }

            /**
             * Sets the value of the traceLambda property.
             *
             * @param value allowed object is {@link Boolean }
             */
            public void setTraceLambda(Boolean value) {
                traceLambda = value;
            }

            /**
             * Gets the value of the traceReturnTypeDescriptors property.
             *
             * <p>
             * This accessor traceReturnTypeDescriptors returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the object.
             * This is why there is not a <CODE>set</CODE> traceReturnTypeDescriptors for the traceReturnTypeDescriptors property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTraceReturnTypeDescriptors().add(newItem);
             * </pre>
             *
             * <p>
             * Objects of the following type(s) are allowed in the list {@link java.lang.String }
             */
            public List<String> getTraceReturnTypeDescriptors() {
                if (traceReturnTypeDescriptors == null) {
                    traceReturnTypeDescriptors = new ArrayList<>();
                }
                return traceReturnTypeDescriptors;
            }

            /**
             * Gets the value of the pattern property.
             *
             * @return possible object is {@link String }
             */
            public String getPattern() {
                return pattern;
            }

            /**
             * Sets the value of the pattern property.
             *
             * @param value allowed object is {@link String }
             */
            public void setPattern(String value) {
                pattern = value;
            }

            /**
             * Gets the value of the includeNonstatic property.
             *
             * @return possible object is {@link Boolean }
             */
            public boolean getIncludeNonstatic() {
                return includeNonstatic;
            }

            /**
             * Sets the value of the includeNonstatic property.
             *
             * @param value allowed object is {@link Boolean }
             */
            public void setIncludeNonstatic(boolean value) {
                includeNonstatic = value;
            }

            /**
             * Gets the value of the transactionType property.
             *
             * @return possible object is {@link String }
             */
            public String getTransactionType() {
                if (transactionType == null) {
                    return "background";
                } else {
                    return transactionType;
                }
            }

            /**
             * Sets the value of the transactionType property.
             *
             * @param value allowed object is {@link String }
             */
            public void setTransactionType(String value) {
                transactionType = value;
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="includeSubclasses" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             */
            public static class ClassName {
                protected String value;
                protected boolean includeSubclasses;

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is {@link String }
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the includeSubclasses property.
                 *
                 * @return possible object is {@link Boolean }
                 */
                public boolean isIncludeSubclasses() {
                    return includeSubclasses;
                }

                /**
                 * Sets the value of the includeSubclasses property.
                 *
                 * @param value allowed object is {@link Boolean }
                 */
                public void setIncludeSubclasses(Boolean value) {
                    includeSubclasses = value;
                }
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice>
             *         &lt;element name="returnType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;sequence>
             *           &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *           &lt;element name="parameters" minOccurs="0">
             *             &lt;complexType>
             *               &lt;complexContent>
             *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                   &lt;sequence>
             *                     &lt;element name="type" maxOccurs="unbounded" minOccurs="0">
             *                       &lt;complexType>
             *                         &lt;simpleContent>
             *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                             &lt;attribute name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;/extension>
             *                         &lt;/simpleContent>
             *                       &lt;/complexType>
             *                     &lt;/element>
             *                   &lt;/sequence>
             *                 &lt;/restriction>
             *               &lt;/complexContent>
             *             &lt;/complexType>
             *           &lt;/element>
             *         &lt;/sequence>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            public static class Method {
                protected String returnType;
                protected String name;
                protected Extension.Instrumentation.Pointcut.Method.Parameters parameters;

                /**
                 * Gets the value of the returnType property.
                 *
                 * @return possible object is {@link String }
                 */
                public String getReturnType() {
                    return returnType;
                }

                /**
                 * Sets the value of the returnType property.
                 *
                 * @param value allowed object is {@link String }
                 */
                public void setReturnType(String value) {
                    returnType = value;
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is {@link String }
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is {@link String }
                 */
                public void setName(String value) {
                    name = value;
                }

                /**
                 * Gets the value of the parameters property.
                 *
                 * @return possible object is {@link Extension.Instrumentation.Pointcut.Method.Parameters }
                 */
                public Extension.Instrumentation.Pointcut.Method.Parameters getParameters() {
                    return parameters;
                }

                /**
                 * Sets the value of the parameters property.
                 *
                 * @param value allowed object is {@link Extension.Instrumentation.Pointcut.Method.Parameters }
                 */
                public void setParameters(Extension.Instrumentation.Pointcut.Method.Parameters value) {
                    parameters = value;
                }

                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="type" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;simpleContent>
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                 &lt;attribute name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *               &lt;/extension>
                 *             &lt;/simpleContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 */
                public static class Parameters {
                    protected List<Extension.Instrumentation.Pointcut.Method.Parameters.Type> type;

                    /**
                     * Gets the value of the type property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the object.
                     * This is why there is not a <CODE>set</CODE> method for the type property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getType().add(newItem);
                     * </pre>
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Extension.Instrumentation.Pointcut.Method.Parameters.Type }
                     */
                    public List<Extension.Instrumentation.Pointcut.Method.Parameters.Type> getType() {
                        if (type == null) {
                            type = new ArrayList<>();
                        }
                        return type;
                    }

                    /**
                     * <p>Java class for anonymous complex type.
                     *
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType>
                     *   &lt;simpleContent>
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *       &lt;attribute name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *     &lt;/extension>
                     *   &lt;/simpleContent>
                     * &lt;/complexType>
                     * </pre>
                     */
                    public static class Type {
                        protected String value;
                        protected String attributeName;

                        /**
                         * Gets the value of the value property.
                         *
                         * @return possible object is {@link String }
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         *
                         * @param value allowed object is {@link String }
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the attributeName property.
                         *
                         * @return possible object is {@link String }
                         */
                        public String getAttributeName() {
                            return attributeName;
                        }

                        /**
                         * Sets the value of the attributeName property.
                         *
                         * @param value allowed object is {@link String }
                         */
                        public void setAttributeName(String value) {
                            attributeName = value;
                        }
                    }
                }
            }

            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            public static class NameTransaction {
            }
        }
    }
}
