query getTaskAndUser {
    getTask(id: "0x3") {
        id
        title
        completed
    }
    queryUser(filter: {username: {eq: "dgraphlabs"}}) {
        username
        name
    }
}

query completedTasks {
    queryTask(filter: {completed: true}) {
        title
        completed
    }
}