name: Setup Environment
description:  Sets up the environment to build/test the agent.
inputs:
  gradle-cache-read-only:
    description: 'Whether the Gradle cache should be read only'
    required: false
    default: 'true'
# This action expects the agent to be checked out at $GITHUB_WORKSPACE.
# It will also set up the instrumentation jar zip if AWS credentials are set.
# This action requires these because composite actions cannot use secrets.

runs:
  using: composite

  steps:
    - name: Set up Javas
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # pin to v4.8.0
      with:
        distribution: 'temurin'
        java-version: |
          25
          21
          17
          11
          8

    - name: set gradle.properties
      shell: bash
      run: |
        sed -i -e "s|jdk8=8|jdk8=${JAVA_HOME_8_X64}|
        s|jdk11=11|jdk11=${JAVA_HOME_11_X64}|
        s|jdk17=17|jdk17=${JAVA_HOME_17_X64}|
        s|jdk21=21|jdk21=${JAVA_HOME_21_X64}|
        s|jdk25=25|jdk25=${JAVA_HOME_25_X64}|" gradle.properties.gha
        cat gradle.properties.gha >> gradle.properties

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # pin to v4.4.0
      with:
        cache-read-only: ${{ inputs.gradle-cache-read-only }}
        validate-wrapper: false

    - name: Setup Gradle options
      shell: bash
      run: echo "GRADLE_OPTIONS=--console=plain --parallel -Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.fromEnv=JAVA_HOME_8_X64,JAVA_HOME_11_X64,JAVA_HOME_17_X64,JAVA_HOME_21_X64,JAVA_HOME_25_X64" >> $GITHUB_ENV

    - name: Download S3 instrumentation jar zip
      shell: bash
      run: |
        aws s3 cp s3://nr-java-agent-s3-instrumentation/proprietary-jars-20230623.zip proprietary-jars.zip && unzip proprietary-jars.zip
        if [ $? -ne 0 ]; then
          echo "Instrumentation jar zip unavailable." >> $GITHUB_STEP_SUMMARY
        fi
