name: Setup Environment
description:  Sets up the environment to build/test the agent.
# This action expects the agent to be checked out at $GITHUB_WORKSPACE and K2 at $GITHUB_WORKSPACE/k2-javaagent.
# It will also set up the instrumentation jar zip if S3 credentials are set.
# This action requires these because composite actions cannot use secrets.

runs:
  using: composite

  steps:
    - name: Set up Javas
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: |
          20
          19
          17
          11
          8

    # Rewrite gradle.properties
    - name: set gradle.properties
      shell: bash
      run: |
        sed -i -e "s|jdk8=8|jdk8=${JAVA_HOME_8_X64}|
        s|jdk11=11|jdk11=${JAVA_HOME_11_X64}|
        s|jdk17=17|jdk17=${JAVA_HOME_17_X64}|
        s|jdk19=19|jdk19=${JAVA_HOME_19_X64}|
        s|jdk20=20|jdk20=${JAVA_HOME_20_X64}|" gradle.properties.gha
        cat gradle.properties.gha >> gradle.properties

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Setup Gradle options
      shell: bash
      run: echo "GRADLE_OPTIONS=-Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.fromEnv=JAVA_HOME_8_X64,JAVA_HOME_11_X64,JAVA_HOME_17_X64,JAVA_HOME_19_X64,JAVA_HOME_20_X64" >> $GITHUB_ENV

    - name: Download S3 instrumentation jar zip
      shell: bash
      run: |
        aws s3 cp s3://nr-java-agent-s3-instrumentation/proprietary-jars-20220805.zip proprietary-jars.zip && unzip proprietary-jars.zip  
        if [ $? -ne 0 ]; then
          echo "Instrumentation jar zip unavailable." >> $GITHUB_STEP_SUMMARY
        fi
