FROM eclipse-temurin:17.0.15_6-jdk-ubi9-minimal

WORKDIR /app

# Install dependencies for gradle
RUN microdnf install -y unzip findutils

# Build the app
COPY ./petclinic/gradle/ gradle
COPY ./petclinic/gradlew ./
COPY ./petclinic/build.gradle ./
COPY ./petclinic/settings.gradle ./

COPY ./petclinic/src ./src

RUN ./gradlew bootJar

# Everything else below is boilerplate needed to run

# Copy test cases file (these contain different agent configurations)
COPY ./test_cases test_cases

# Copy test cases file (these contain different agent configurations)

# Copy jmeter test plan file (these configure the load size and what performance data to gather like request throughput and JMX metrics)
COPY ./jmeter.jmx ./

# COPY start.sh script which starts up your app
COPY ./start.sh ./

# COPY config.sh script which contains various configurations in the form of environment variables.
COPY ./config.sh ./

# Set the start script to be entrypoint.sh (this will be provided via volume mounts)
CMD ["sh", "/app/entrypoint.sh"]