query {
    FIRST: libraries (id: 123, name: "me bro") {
        branch
        booksInStock (password: "hide me") {
            title (id: 123),
            author
        }
        bathroomReading: magazinesInStock (password: "hide me") {
            magissue,
            magtitle
        }
    }
    SECOND: Slibraries (id: 456, name: "no bro") {
        Sbranch
        profitCenter: SbooksInStock (password: "hide me") {
            Sisbn,
            Stitle,
        }
        SmagazinesInStock (password: "hide me") {
            Smagissue,
            Smagtitle
        }
    }
}