mutation {
    writePost(title: ***, text: ***, category: ***, author: ***) {
        id
        title
        category
        text
        author {
            id
            name
            thumbnail
        }
    }
}