mutation {
    writePost(title: "New Post2", text: "Text", category: null, author: "Author2") {
        id
        title
        category
        text
        author {
            id
            name
            thumbnail
        }
    }
}