dependencies {
    implementation(project(":agent-bridge"))
    implementation("software.amazon.awssdk:kinesis:2.1.0")
}

jar {
    manifest { attributes 'Implementation-Title': 'com.newrelic.instrumentation.aws-java-sdk-kinesis-2.1.0' }
}

verifyInstrumentation {
    versionGrouping 'LATEST_MINOR'
    passesOnly 'software.amazon.awssdk:kinesis:[2.1.0,)'
    excludeRegex ".*preview.*"
}

site {
    title 'AWS Kinesis'
    type 'Framework'
}