query {
    libraries {
        branch
        booksInStock {
            isbn,
            title,
            author
        }
        magazinesInStock {
            issue,
            title
        }
    }
}