#!/bin/sh

# Verify the commit message contains a Jira id
#
# Previous versions of this also checked that the branch name contained the Jira number but we've removed that
msg=$(<$1)

shopt -s nocasematch

# Commit message will be OK if it contains a ref to the Jira number using the Smart Commit syntax
# or...if it starts with "Merge". Kept that last bit from the past impl
#
# Note that since our new Jira instances supports both the internal (NR) naming and the public (NEWRELIC), we test for both
if [[ ! "$msg" =~ ^((NR|NEWRELIC)-[0-9]+[ ]+\#.*)|merge ]]; then
  echo "Aborting commit. Your commit message must be a Jira Smart Commit, starting with ('NR-xxx #comment' or 'NEWRELIC-xxx #comment') or 'Merge'"
  exit 1
fi
