/*
 *
 *  * Copyright 2020 New Relic Corporation. All rights reserved.
 *  * SPDX-License-Identifier: Apache-2.0
 *
 */

package com.newrelic.agent.util.asm;

import java.io.IOException;
import java.lang.reflect.Proxy;

/**
 * This exception is thrown when the agent can't read the bytes of a class for a well understood (and harmless) reason.
 * For instance, if the class was generated by {@link Proxy}.
 */
public class BenignClassReadException extends IOException {
    private static final long serialVersionUID = -6999790175012592488L;

    public BenignClassReadException(String message) {
        super(message);
    }
}
