query {
  FIRST: libraries (id: 123, name: "me bro") {
     branch
    booksInStock {
      title,
      author
    }
    bathroomReading: magazinesInStock {
      magissue,
      magtitle
    }
  }
    SECOND: Slibraries (id: 456, name: "no bro") {
      Sbranch
      profitCenter: SbooksInStock {
        Sisbn,
        Stitle,
      }
      SmagazinesInStock {
        Smagissue,
        Smagtitle
      }
    }
}