plugins {
    id "org.jetbrains.kotlin.jvm"
}

dependencies {
    implementation(project(":agent-bridge"))
    implementation("io.quarkus:quarkus-resteasy:2.14.1.Final")
}

jar {
    manifest { attributes 'Implementation-Title': 'com.newrelic.instrumentation.quarkus-resteasy-2.14.1',
            'Implementation-Title-Alias': 'quarkus'}
}

verifyInstrumentation {
    versionGrouping 'LATEST_MINOR'
    passesOnly 'io.quarkus:quarkus-resteasy:[2.14.1.Final,)'
    excludeRegex '.*CR[0-9]*'
    excludeRegex '.*Alpha[0-9]'
    excludeRegex '.*Beta[0-9]'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

test {
    onlyIf {
        !project.hasProperty('test8') && !project.hasProperty('test11')
    }
}

site {
    title 'Quarkus RestEasy Classic'
    type 'Framework'
}