dependencies {
    implementation 'org.redisson:redisson:3.17.6'

    implementation(project(":agent-bridge"))

    testImplementation 'junit:junit:4.12'
    testImplementation fileTree(include: ['*.jar'], dir: '../test-lib')
    testImplementation 'com.github.kstyrc:embedded-redis:0.6'
    testImplementation 'org.slf4j:slf4j-api:1.7.32'
    testImplementation 'org.slf4j:slf4j-simple:1.7.32'
}

jar {
    manifest {
        attributes 'Implementation-Title': 'com.newrelic.instrumentation.redisson-3.17.6'
    }
}


verifyInstrumentation {
    passes 'org.redisson:redisson:[3.17.6,3.19.2)'
    excludeRegex '.*-NR.*'
}
