# Workflow: Dependency Graph Submission and Vulnerability Reporting
#
# Trigger: This workflow runs on every merge to the main branch.
#
# Purpose: It generates and submits a dependency graph to the GitHub Dependency Submission API. The graph is used to
# trigger Dependabot Alerts for vulnerable dependencies, and to populate the Dependency Graph insights view in GitHub.
#

name: Dependency Submission

on:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          ref: 'main'

      - name: Set gradle.properties Workaround
        shell: bash
        run: |
          echo "jdk8=/tmp" >> gradle.properties
          echo "jdk11=/tmp" >> gradle.properties
          echo "jdk17=/tmp" >> gradle.properties
          echo "jdk21=/tmp" >> gradle.properties

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # pin@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # pin@v6
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
          dependency-graph-exclude-projects: ':instrumentation'
          dependency-graph-include-configurations: '.*(shadowIntoJar|jarIntoJar)'
