name: GHA-AIT-functionality-trace-tests

on:
  pull_request:
    branches: [ disabled ] ## branches TBD
    types: [assigned, opened, synchronize, reopened, ready_for_review] # Types TBD
  push:
    branches: [ disabled ]
  workflow_dispatch:
    inputs:
      BRANCH:
        description: "Specify branch (main is default)"
        required: false
        default: 'main'

jobs:
  AIT_func_trace:
    # needs: install-all-java
    timeout-minutes: 120
    runs-on: ubuntu-latest
    # Determine if easier to make the env strings below part of the matrix
    env:
      java_func_path: "tests/java/functionality"
      java_func_type: "trace"
      default-branch: "main"
    strategy:
      ##max-parallel: 1 ## used to force sequential
      fail-fast: false
      matrix:
        # func_path: [akka, ejb, jaxrs, jms, netty, play, quartz, snap, spring, thrift]
        func_tests:
          - tracecontext/__init__.py
          - tracecontext/traceparent.py
          - tracecontext/tracestate.py
          - client.py
          - server.py
          - test.py
          - trace_base.py

    steps:
      - uses: actions/checkout@v2

      ## Ongoing tests with artifactory dependecies
      - name: Checkout AIT repo test
        uses: actions/checkout@v2
        with:
          repository: newrelic/java-agent-integration-tests
          ref: main
          token: ${{ secrets.AITPAT }}
          path: agent-integration-tests

      # Print Environmental variables
      - name: Print Environmental variables
        run: |
          printenv | sort -f

      # Apps repos/caches - this prpcess could be a candidate for custom action
      - name: Checkout Cache 1
        uses: actions/checkout@v2
        with:
          repository: newrelic/java-ait-cache-1
          ref: gha
          token: ${{ secrets.AITPAT }}
          path: appcache1
          lfs: true

      - name: Checkout Cache 2
        uses: actions/checkout@v2
        with:
          repository: newrelic/java-ait-cache-2
          ref: gha
          token: ${{ secrets.AITPAT }}
          path: appcache2
          lfs: true

      - name: Checkout Cache 3
        uses: actions/checkout@v2
        with:
          repository: newrelic/java-ait-cache-3
          ref: gha
          token: ${{ secrets.AITPAT }}
          path: appcache3
          lfs: true

      - name: Checkout Cache 4
        uses: actions/checkout@v2
        with:
          repository: newrelic/java-ait-cache-4
          ref: gha
          token: ${{ secrets.AITPAT }}
          path: appcache4
          lfs: true

      # Consolidate caches into one directory
      - name: Consolidate caches into Apps directory
        run: |
          ls -la
          mkdir apps
          mv appcache1/* apps/
          mv appcache2/* apps/
          mv appcache3/* apps/
          mv appcache4/* apps/
          cd apps
          ls -la
          ls -la java_test_webapp-master/
          cd ../

      ## JDK Installs

      # Install 11
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      # Set the JDk variable
      - name: Set the required JDK variable
        run: |
          echo "ORG_GRADLE_PROJECT_jdk11=${JAVA_HOME}" >> $GITHUB_ENV

      # Install 16
      - name: Set up Java 16
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 16
          cache: 'gradle'

      # Set the JDk variable
      - name: Set the required JDK variable
        run: |
          echo "ORG_GRADLE_PROJECT_jdk16=${JAVA_HOME}" >> $GITHUB_ENV

      # Install 8, last to set JAVA_HOME to 8
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'

      # Set the JDk variable
      - name: Set the required JDK variable
        run: |
          echo "ORG_GRADLE_PROJECT_jdk8=${JAVA_HOME}" >> $GITHUB_ENV

      ## End JDK Install

      # Check ENV variables
      - name: Check environmental variables
        run: printenv | sort -f

      # End Java restore section

      # Restore the gradle cache
      - name: Restore the gradle caches
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle
          restore-keys: |
            ${{ runner.os }}-gradle

      ## TESTING SECTION

      # Replication of steps from AIT README

      # Build the agent jar
      - name: Build newrelicJar
        if: ${{ failure() || success() }}
        run: |
          echo "JAVA_HOME=${ORG_GRADLE_PROJECT_jdk8}" >> $GITHUB_ENV
          echo "REVIEW ANY NEW ITEMS IN WORKSPACE"
          ls -la
          ./gradlew clean jar --parallel
          ls -la newrelic-agent/build/

      - name: Check agent-integration-tests dir.
        run: |
          ls -la agent-integration-tests/

      ## Testing replacing below step with custom action

      ## CUSTOM ACTIONS - DO NOT REMOVE
      # Checkout the private actions repo and then call the action
      # - name: Get private java-actions repo with composite action
      #   uses: actions/checkout@v2
      #   with:
      #     repository: newrelic/java-actions
      #     ref: main
      #     token: ${{ secrets.ACTIONS_TOKEN }}
      #     path: .github/actions

      # Verify java-actions directory
      # - name: Verify ait actions directory
      #   run: |
      #     ls -la .github/actions/ait

      # Call the action
      # - name: Run the AIT action - ${{ matrix.func_tests}}
      #   uses: ./.github/actions/ait

      ## End custom action

      ## WE LOSE THE VIRTUAL ENVIRONMENT ONCE WE LEAVE THE STEP
      - name: Create virtualenv and run AITs - ${{ matrix.func_tests}}
        if: ${{ failure() || success() }}
        run: |
          cd agent-integration-tests
          echo "conf/testenv complains of the path below - creating symlink for now"
          ln -s ${GITHUB_WORKSPACE}/apps /home/runner/apps
          ln -s ${GITHUB_WORKSPACE}/newrelic-agent/build/newrelicJar/newrelic.jar ${GITHUB_WORKSPACE}/newrelic.jar
          echo "still complains of file not found"
          ls -la ${GITHUB_WORKSPACE}
          sudo apt install virtualenv
          virtualenv -p /usr/bin/python3.8 .
          echo "What version of maven are we using?"
          mvn --version
          echo "are the files created?"
          ls -la bin/
          echo "checking conf"
          ls -la conf/
          echo "runnig bin/activate"
          . bin/activate
          bin/pip3 install -r conf/requirements.txt
          echo "run autoconfigure"
          JAVA8JRE=${ORG_GRADLE_PROJECT_jdk8} \
          JAVA11JRE=${ORG_GRADLE_PROJECT_jdk11} \
          JAVA16JRE=${ORG_GRADLE_PROJECT_jdk16} \
          conf/autoconfigure
          echo "running conf/testenv java"
          . conf/testenv java
          echo "check local java config"
          cat conf/java_local_config.yml
          echo "Changing java_agent_dev_root values"
          sed -i 's|java_agent_dev_root: /home/runner/work/newrelic-java-agent/newrelic-java-agent|java_agent_dev_root: /home/runner/work/newrelic-java-agent/newrelic-java-agent/newrelic-agent/build/newrelicJar|' conf/java_local_config.yml
          sed -i 's|app_root: /home/runner/apps|app_root: /home/runner/work/newrelic-java-agent/newrelic-java-agent/apps|' conf/java_local_config.yml
          echo "verifying values have been changed"
          cat conf/java_local_config.yml
          echo "shell variables:"
          set | sort -f
          echo "GENERATE ARTIFACTS"
          ## artifacts section for testing
          mkdir testing-artifacts
          echo "was the dir created?"
          ls -la
          touch testing-artifacts/shell-variables.txt
          touch testing-artifacts/env-variables.txt
          set | sort -f > testing-artifacts/shell-variables.txt
          printenv | sort -f > testing-artifacts/env-variables.txt
          cp conf/java_local_config.yml testing-artifacts/
          echo "check the contents of testing-artifacts"
          ls -la testing-artifacts/
          echo "are we still in agent-integration-tests?"
          pwd
          ## End testing artifacts section
          echo "Check the current value of JAVA_HOME"
          echo "The current JAVA_HOME is ${JAVA_HOME}"
          echo "RUN THE TESTS"
          echo "Running ${{ matrix.func_basic_features }}"
          TEST_LOG_LEVEL=DEBUG TEST_SUPPRESS_METRIC_DEBUG=1 \
          ./bin/runtest.sh ${java_func_path}/${java_func_type}/${{ matrix.func_tests }}

      # Rename matrix item to remove problem characers
      - name: Rename Matrix item
        if: ${{ failure() || success() }}
        env:
          MATRIX: ${{ matrix.func_tests}}
        run: |
          MATRIX_ITEM=$(echo ${MATRIX} | sed 's|/|-|g')
          echo "MATRIX="${MATRIX_ITEM}"" >> $GITHUB_ENV

      # Capture Testing Artifacts
      - name: Capture testing artifacts
        if: ${{ failure() || success() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.workflow }}-${{ github.job }}-${{ env.MATRIX }}
          path: |
            agent-integration-tests/testing-artifacts/*
            **/build/test-results/**/*.xml

      # Print Environmental variables
      - name: Print Environmental variables (verify activate has been sourced)
        if: failure() || success()
        run: |
          printenv |  sort -f
