name: Release - Copy to S3 (Prod)

on:
  workflow_dispatch:
    inputs:
      version_number:
        required: true
        type: string
        description: 'The version being released. Eg. 7.11.0'

jobs:
  copy-to-s3:
    name: Copy files to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Self
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEFAULT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEFAULT }}
          aws-region: us-east-2

      - name: Run script
        env:
          RUNNING_ON_GHA: 'true'
        run: ./automation/release/copy-to-s3.sh staging ${{ inputs.version_number }} default
