name: Test Suite - Release
on:
  workflow_dispatch:
    inputs:
      agent-ref:
        description: "Specify agent branch/tag/sha (main is default)"
        required: false
        default: 'main'
      ait-ref:
        description: "Specify AIT branch/tag/sha (main is default)"
        required: false
        default: 'main'
      cache-ref:
        description: "Specify cache branch/tag/sha (main is default)"
        required: false
        default: 'main'
      wiki-report-desc:
        description: "(Optional) Description for wiki reports (used when publishing ingest metrics and/or performance metrics). NO SPACES. Ex: Release9.0.0"
        required: false
      publish-ingest-metrics:
        description: "Publish ingest metrics to wiki"
        required: false
        type: boolean
        default: false
      publish-performance-metrics:
        description: "Publish AIT performance metrics to wiki"
        required: false
        type: boolean
        default: false

jobs:

  aits:
    uses: ./.github/workflows/Test-AITs.yml
    with:
      agent-ref: ${{ inputs.agent-ref || github.sha || 'main' }}
      ait-ref: ${{ inputs.ait-ref || 'main' }}
      cache-ref: ${{ inputs.cache-ref || 'main' }}
      wiki-report-desc: ${{ inputs.wiki-report-desc }}
      publish-ingest-metrics: ${{ inputs.publish-ingest-metrics }}
      publish-performance-metrics: ${{ inputs.publish-performance-metrics }}
    secrets: inherit

  functional-tests:
    uses: ./.github/workflows/GHA-Functional-Tests.yaml
    with:
      agent-ref: ${{ inputs.agent-ref || github.sha || 'main' }}
    secrets: inherit

  functional-tests-scala:
    uses: ./.github/workflows/GHA-Scala-Functional-Tests.yaml
    with:
      agent-ref: ${{ inputs.agent-ref || github.sha || 'main' }}
    secrets: inherit

  instrumentation-tests:
    uses: ./.github/workflows/Java-Instrumentation-Tests.yml
    with:
      agent-ref: ${{ inputs.agent-ref || github.sha || 'main' }}
    secrets: inherit

  instrumentation-tests-scala:
    uses: ./.github/workflows/GHA-Scala-Instrumentation-Tests.yaml
    with:
      agent-ref: ${{ inputs.agent-ref || github.sha || 'main' }}
    secrets: inherit

  unit-tests:
    uses: ./.github/workflows/GHA-Unit-Tests.yaml
    with:
      agent-ref: ${{ inputs.agent-ref || github.sha || 'main' }}
    secrets: inherit

  verify-unshadowed-jars:
    uses: ./.github/workflows/VerifyUnshadowedJars.yml
    with:
      agent-ref: ${{ inputs.agent-ref || github.sha || 'main' }}
    secrets: inherit

  verify-instrumentation:
    uses: ./.github/workflows/VerifyInstrumentation.yml
    with:
      agent-ref: ${{ inputs.agent-ref || github.sha || 'main' }}
    secrets: inherit
