name: Verify Instrumentation (single)

# Permissions granted to all jobs in the workflow.
# Permissions that aren't explicitly defined here will default to a value of none.
permissions: {}

on:
  workflow_dispatch:
    inputs:
      module:
        required: true
        type: string
        description: 'The directory of the module to verify.'
      ref:
        required: true
        default: main
        type: string
        description: 'The ref (branch, SHA, tag?) to run the tests on'
      grouping:
        required: false
        default: ''
        type: string
        description: 'The versionGrouping scheme to apply to the verify task (one among: [ALL, LATEST_MINOR, LATEST_MAJOR, LATEST]).'

env:
  MODULE_AS_LIST: ${{ format('[{0}]', toJson(inputs.module)) }}

jobs:
  build-agent:
    name: Build agent
    uses: ./.github/workflows/X-Reusable-BuildAgent.yml
    with:
      agent-ref: ${{ github.sha }}
    secrets: inherit

  verify-module:
    name: Verify module
    needs: build-agent
    uses: ./.github/workflows/X-Reusable-VerifyInstrumentation.yml
    with:
      ref: ${{ inputs.ref }}
      explicit-modules-list: ${{ env.MODULE_AS_LIST }}
      grouping: ${{ inputs.grouping }}
    secrets: inherit
