name: Verify Instrumentation

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: main
        type: string
        description: 'The ref (branch, SHA, tag?) to run the tests on'
  schedule:
    - cron: '0 8 * * *'

# GHA Matrix strategy only allows 255 entries.
# So 2 pages should be good until we have around 500 instrumentation modules
# When we grow to more than that, we'll need to create a third job here and have pages 1/3, 2/3 and 3/3
jobs:
  verify-instrumentation-1:
    name: Page 1/2
    uses: ./.github/workflows/X-Reusable-VerifyInstrumentation.yml
    with:
      page: 1/2
      ref: ${{ github.event.inputs.ref || 'main' }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  verify-instrumentation-2:
    name: Page 2/2
    uses: ./.github/workflows/X-Reusable-VerifyInstrumentation.yml
    with:
      page: 2/2
      ref: ${{ github.event.inputs.ref || 'main' }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
