# Reusable workflow to run Verify Instrumentation on modules.
# Only processes a fraction of the modules so the they fit into a GHA matrix (which is limited to 255 jobs).

# This workflow does not use the setup-gradle action on purpose. That action retrieves over 1GB from the cache
# and when many runners do that at the same time, the cache server returns 429s (Too many requests).

name: X - Reusable Verify Instrumentation

# Permissions granted to all jobs in the workflow.
# Permissions that aren't explicitly defined here will default to a value of none.
permissions: {}

on:
  workflow_call:
    inputs:
      page:
        required: false
        default: '1/1'
        type: string
        description: 'The page to process (eg: 1/2 or 5/5). Ignored when explicit-modules-list is set.'
      explicit-modules-list:
        # A JSON array of module directory names (eg: '["kafka-clients-3.6.0","spring-webmvc-6.0.0"]').
        # When set, this explicit list is used instead of paginating everything in the instrumentation/** directory.
        # Since pagination is skipped, callers should ensure that this list is not too long (<250 modules).
        required: false
        default: ''
        type: string
        description: 'Explicit JSON array of module names to verify. If set, pagination will be skipped.'
      ref:
        required: true
        default: main
        type: string
        description: 'The ref (branch, SHA, tag?) to run the tests on'
      grouping:
        #One of [ALL, LATEST_MINOR, LATEST_MAJOR, LATEST].
        #If not set, falls back to a module's locally configured grouping or ALL.
        required: false
        default: ''
        type: string
        description: 'The versionGrouping scheme to apply to the verify task (eg: LATEST_MAJOR)'

jobs:
  # this job reads the directories in newrelic-java-agent/instrumentation and creates a JSON with the list of the modules
  # this list is paginated and will be used in the verify-module job.
  # when inputs.modules-json is provided, that explicit list is used as-is instead.
  read-modules:
    runs-on: ubuntu-24.04
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
#       - uses: GitHubSecurityLab/actions-permissions/monitor@v1 # detects minimum permissions required to run the workflow, uncomment to use
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        # Only the implicit/paginated version of this action requires the checkout (so we can read the contents of instrumentation/**)
        if: ${{ inputs.explicit-modules-list == '' }}
        with:
          ref: ${{ inputs.ref }}

      - id: set-modules
        name: get instrumentation modules as json
        run: |
          # parses the explicit modules list if one was provided
          if [ -n '${{ inputs.explicit-modules-list }}' ]; then
            modules=$(jq -c -n --argjson modules '${{ inputs.explicit-modules-list }}' '{ "modules": $modules }')
            echo "modules=$modules" >> $GITHUB_OUTPUT
            exit 0
          fi

          # if no explicit modules list was provided, parse all modules out of the instrumentation directory
          cd instrumentation
          tmpfile=$(mktemp /tmp/dirs.XXXXXXXXXX)
          # lists the folders inside instrumentation, and removes the trailing '/'
          ls -d */ | cut -d'/' -f 1 > $tmpfile
          # creates an envar with the requested page of the instrumentation modules in a JSON format
          modules=$((
            echo '{ "modules" : '
            split -n l/${{ inputs.page }} $tmpfile | jq -R -s -c 'split("\n")[:-1]'
            echo " }"
          ) | jq -c .)
          # save the output of the job
          echo "modules=$modules" >> $GITHUB_OUTPUT

  verify-module:
    name: ${{ matrix.modules }}
    runs-on: ubuntu-24.04
    needs: read-modules
    strategy:
      fail-fast: false
      max-parallel: 7
      # GHA's IDE think the line below is broken. It is not.
      matrix: ${{ fromJson(needs.read-modules.outputs.modules) }}
    steps:
#       - uses: GitHubSecurityLab/actions-permissions/monitor@v1 # detects minimum permissions required to run the workflow, uncomment to use
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Retrieve agent from cache
        id: retrieve-agent
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # pin@v5.0.5 # pin@v5
        with:
          path: /home/runner/work/newrelic-java-agent/newrelic-java-agent/newrelic-agent/build/newrelicJar/newrelic.jar
          key: agent-jar-${{ github.run_id }}
          fail-on-cache-miss: true

      # Verify instrumentation must run on the MAXIMUM CONFIGURED toolchain version among all instrumentation modules.
      # Currently, the maximum configured toolchain in this project is Java 17.
      # If you added an instrumentation module with a toolchain > 17, and this job is failing, that may be why.
      # Increase JAVA_HOME to the new maximum configured toolchain version.
      - name: Running verifyInstrumentation on (${{ matrix.modules }}) (all versions)
        if: ${{ inputs.grouping == ''}}
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: ./gradlew $GRADLE_OPTIONS --info :instrumentation:${{ matrix.modules }}:verifyInstrumentation

      - name: Running verifyInstrumentation on (${{ matrix.modules }}) (limited versions)
        if: ${{ inputs.grouping != ''}}
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        run: ./gradlew $GRADLE_OPTIONS --info :instrumentation:${{ matrix.modules }}:verifyInstrumentation  -PversionGrouping=${{ inputs.grouping }}
